### PR TITLE
code cleanup

### PR DESCRIPTION
**Pull request by The-Forecaster**
You should consider converting the Feature classes into objects and all classes that use "instance" can also be converted into objects.

### CODE REVIEW

**Comment by cattyngmd** [comment]
mfw kotlin 💀

**Comment by The-Forecaster** [comment]
I LOVE KOTLIN I LOVE KOTLIN

**Comment by chell-dev** [comment]
>code cleanup

>2600 changes

didn't have to do me like that man

**Comment by chell-dev** [comment]
I don't want none of that intellij cleanup, but the event manager looks good. So you can make a pr with only that or edit this one idk im bad at github.
I remembered that objects exist a couple days ago too so I'm working on it, but thanks for the tip.
Also, respectfully, I'll generate the wrapper myself instead of trusting a jar file from a stranger. Thanks for pointing it out tho!

**Pull request closed without merging**
